type: object
properties:
  id:
    type: string
    format: uuid
    description: Unique identifier representing a specific product
  description:
    type: string
    description: Description of the product
  dimensions:
    $ref: dimensions.yaml
  categories:
    type: array
    items:
      $ref: category.yaml
  images:
    type: array
    items:
      $ref: image.yaml
  price:
    type: string
    pattern: ^-?(?:0|[1-9]\d{0,2}(?:,?\d{3})*)(?:\.\d+})?$
  cost:
    type: string
    pattern: ^-?(?:0|[1-9]\d{0,2}(?:,?\d{3})*)(?:\.\d+})?$
  dateCreated:
    type: string
    format: date-time
    description: Date and time the product was created
  dateUpdated:
    type: string
    format: date-time
    description: Date and time the product was last updated