openapi: 3.0.0
info:
  version: 1.0.0
  title: API First with Spring Boot
  termsOfService: https://example.com/terms/
  contact:
    name: Contact our support
    email: vldburlacu@yahoo.com
    url: https://spring-framework.guru
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
    altText: OpenAPI example logo
  description: >
    This is an **example** API to demonstrate features of the OpenAPI
    specification.

    # Introduction

externalDocs:
  description: "Find out how to create a GitHub repo for your OpenAPI definition."
  url: 'https://github.com/Redocly/create-openapi-repo'
tags:
  - name: Customer
    description: "Customer operations"
  - name: Product
    description: "Product Operations"
servers:
  - url: https://{tenant}/api/v1
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: https://springframework.guru/api/v1
paths:
  '/v1/customers':
    $ref: 'paths/v1/customers.yaml'
  '/v1/customers/{customerId}':
    $ref: 'paths/v1/customers_{customerId}.yaml'
  '/v1/products':
    $ref: 'paths/v1/products.yaml'
  '/v1/products/{productId}':
    $ref: 'paths/v1/products_{productId}.yaml'
  '/v1/orders':
    $ref: 'paths/v1/orders.yaml'
  '/v1/orders/{orderId}':
    $ref: 'paths/v1/orders_{orderId}.yaml'
security:
  - basic_auth: []
components:
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic