get:
  tags:
    - Product
  summary: Get a product by ID
  description: Get a product by ID
  operationId: getProductById
  parameters:
    - name: productId
      in: path
      description: The ID of the product to retrieve
      required: true
      schema:
        type: string
        format: uuid
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/v1/product.yaml
    '400':
      description: Bad Request
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/Problem.yaml
put:
    tags:
        - Product
    summary: Update a product by ID
    description: Update a product by ID
    operationId: updateProductById
    parameters:
        - name: productId
          in: path
          description: The ID of the product to update
          required: true
          schema:
            type: string
            format: uuid
    requestBody:
        description: Product to update
        required: true
        content:
          application/json:
            schema:
              $ref: ../../components/schemas/v1/product_update.yaml
    responses:
      '200':
        description: Successfully operation
        content:
          application/json:
            schema:
              $ref: ../../components/schemas/v1/product.yaml
      '400':
        description: Bad Request
      '404':
        description: Not Found